### ISSUE TITLE
'발표자 뽑기' 클릭 후 '데이터 설정' 클릭 시 참여자 추가가 안됨

### ISSUE THREAD

**Issue by pastelmind** [hustle-dev/random-presenter-picker#1]
## How to Reproduce

1. LocalStorage가 설정되지 않은 브라우저에서 웹앱(https://random-presenter-picker.vercel.app/<wbr>)에 접속합니다.
    - LocalStorage를 지우거나, 브라우저의 시크릿 모드를 사용하면 됩니다.
2. '발표자 뽑기'를 클릭합니다.
    1. '데이터 설정 버튼을 눌러 발표자 데이터를 설정해주세요' 창이 뜨면 '닫기'를 클릭합니다
3. '데이터 설정'을 클릭합니다.
4. 새로 추가할 스터디 참여자의 이름을 입력한 뒤 '입력'을 클릭합니다.

## Expected result

새로운 스터디 참여자가 추가됩니다.

## Actual result

새로운 스터디 참여자가 추가되지 않습니다.

콘솔을 켜면 다음 오류가 출력됩니다.

```
Uncaught TypeError: Cannot read properties of null (reading 'push')
    at HTMLElement.<anonymous> (index.js:148:11)
(anonymous) @ index.js:148
```

<img width="696" alt="random-presenter-picker-error" src="https://user-images.githubusercontent.com/29533079/182502721-f1e01fec-c0a7-4127-a98f-48fb4dbacef6.png">

## More info

다음 코드가 원인으로 보입니다:
https://github.com/hustle-dev/random-presenter-picker/blob/b10ddd35b96c127670354882e85e28dfbf63526f/src/js/index.js#L54

LocalStorage에 값이 없는 경우 `getItem()`은 null을 리턴하기 때문에 `nameArr`이 null로 설정됩니다. 이후 `nameArr.push()`를 실행하면 오류가 발생합니다.

**Comment by hustle-dev** [comment]
상세한 오류 발생 로그 첨부해 주셔서 감사합니다. 

빠른시일내에 오류 수정해서 반영하고, 리팩터링과 마이그레이션 진행하여 더 좋은 앱으로 만들겠습니다. 
감사합니다. 🙂

**Comment by hustle-dev** [comment]
에러 해결하였습니다. 
→ [fix: participatnts adding error](https://github.com/hustle-dev/random-presenter-picker/commit/f8e8325b707fe6ac88b83375c386b057ca887f4b) 

이슈 감사합니다.

> 추가적으로 더 좋은 환경을 위한 `Next.js`로 마이그레이션 진행중입니다.
